Add ClusterIssuer test
giantswarm/cluster-test-suites pull request #76
Opened 2023-08-30 11:21 UTC by ubergesundheit

This PR adds a test to check if the ClusterIssuers installed by cert-manager-app will reach Ready state

2023-08-31 06:56 UTC, ubergesundheit commented
/run cluster-test-suites

2023-08-31 07:33 UTC, ubergesundheit commented
/run cluster-test-suites

2023-08-31 08:50 UTC, AverageMarcus requested changes
> CAPZ test failure is expected. 

How are we fixing it? We can't merge this in without it passing or we'll block other people working.

2023-08-31 08:52 UTC, ubergesundheit commented
> How are we fixing it? 

Any way to use this cluster-test-suites version in https://github.com/giantswarm/default-apps-azure/pull/150 ?

2023-08-31 08:52 UTC, AverageMarcus commented on common/certmanager.go
> +	return fmt.Errorf("ClusterIssuer '%s' is not Ready", clusterIssuerName)
To give some progress update while the test is running: 
```suggestion
    logger.Log("ClusterIssuer '%s' is not Ready", clusterIssuerName)
	return fmt.Errorf("ClusterIssuer '%s' is not Ready", clusterIssuerName)
```

2023-08-31 08:57 UTC, ubergesundheit commented on common/certmanager.go
> +    logger.Log("ClusterIssuer '%s' is not Ready", clusterIssuerName)
```suggestion
		logger.Log("ClusterIssuer '%s' is not Ready", clusterIssuerName)
```

2023-08-31 08:57 UTC, AverageMarcus commented
Not in CI 😞  You can when running locally by setting the `E2E_OVERRIDE_VERSIONS`.

Easiest option would be to get that PR merged in and released then once the new version is available you can re-run the tests on this PR to ensure they're passing.

2023-08-31 08:57 UTC, ubergesundheit commented on common/certmanager.go
> +		logger.Log("ClusterIssuer '%s' is not Ready", clusterIssuerName)
```suggestion
	logger.Log("ClusterIssuer '%s' is not Ready", clusterIssuerName)
```

2023-08-31 08:58 UTC, ubergesundheit commented
> Not in CI 😞 You can when running locally by setting the `E2E_OVERRIDE_VERSIONS`.
> 
> Easiest option would be to get that PR merged in and released then once the new version is available you can re-run the tests on this PR to ensure they're passing.

ok fair enough :+1:

2023-09-01 10:17 UTC, AverageMarcus approved these changes

2023-09-01 11:26 UTC, merged